Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled:	false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Style/ClassVars:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false
